### ISSUE TITLE
x2 pretrained model

### ISSUE THREAD

**Issue by cspk17** [TencentARC/MM-RealSR#1]
Thank you for sharing a excellent work!!
Currently, it seems that only the pretrained models with the scaling factor 4 are shared. 
I would appreciate it if you could share the models with the scaling factor 2.
I want to test both scaling factors.

**Comment by MC-E** [comment]
Thank you for your attention. We did not explore x2 super-resolution in this work. You can simply retrain our model by modifying 'scale' in the option file.

**Comment by cspk17** [comment]
@MC-E I got it. Thank you for your response. I will try it.
