### ISSUE TITLE
However, it is still hard to directly apply our method to train on real samples？

### ISSUE THREAD

**Issue by universea** [TencentARC/MM-RealSR#10]
Limitations. Our MM-RealSR adopts the complex and high-order degradation synthesis [43,35] to simulate the real-world degradations. **However, it is still hard to directly apply our method to train on real samples.** There are also some failure cases (e.g., local jitter in Fig. 6, and our UDEM regards some art effects such as bokeh as degradation).

Hi, 

我看论文的时候发现了这句话, **However, it is still hard to directly apply our method to train on real samples.**，这个意思是不好直接在其它场景上训练吗？我现在是有一些特殊场景的高清和低分辨率的图像，想用这个模型训练一下，让他更适合这种场景，可以吗？

谢谢！

**Comment by universea** [comment]
然后我们这个模型的预测速度怎么样呀？我看论文里没做这块的对比和分析
感谢！

**Comment by MC-E** [comment]
很抱歉回复迟了。“However, it is still hard to directly apply our method to train on real samples” 这句话的含义是目前的训练还是需要成对的仿真数据，但真实场景下的数据其实是难以获得或者不成对的。如果你的数据是成对的，那是可以的直接用的。

**Comment by MC-E** [comment]
这个模型的推理速度与Real-ESRGAN相近，退化预测模块的复杂度相对较低

**Comment by universea** [comment]
> 这个模型的推理速度与Real-ESRGAN相近，退化预测模块的复杂度相对较低

好的，非常感谢！
