### ISSUE TITLE
More fine-grained degradation score

### ISSUE THREAD

**Issue by mrluin** [TencentARC/MM-RealSR#8]
Hello,

Thanks for your great work!

Did you try to predict more fine-grained degradation score? e.g., predicting socre for Gaussian noise, Poisson noise and JPEG compression noise indenpendently instead of predicting one socre.

Looking forward to your reply, thanks.

**Comment by MC-E** [comment]
Thanks for your attention. Yes, our model can predict the relative strength of these simple degradation. But the score does not correspond to the real value.

**Comment by mrluin** [comment]
Thanks for your reply.

Sure, I understand that the predicted score is relative strength. In the paper, the model generally predicts types of noises (i.e., poisson noise, gaussian noise and JPEG compression noise) using one unified noise branch. I mean, will the multiple branch design (e.g., one branch for one type of noise) benefit the performance?

**Comment by CuddleSabe** [comment]
> Thanks for your reply.
> 
> Sure, I understand that the predicted score is relative strength. In the paper, the model generally predicts types of noises (i.e., poisson noise, gaussian noise and JPEG compression noise) using one unified noise branch. I mean, will the multiple branch design (e.g., one branch for one type of noise) benefit the performance?

I don't think so...because the same degrade level in different order, they sees like so different
